name: Deploy website
on: workflow_run
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deploy-dist # any name
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get artifacts
        uses: actions/download-artifact@v3
        with:
          name: deploy-dist # same name as mentioned in the store step
      - name: output
        run: ls
      - name: Deploy
        run: echo "Deploying..."
